In [3]:
from plotly.data import gapminder

gapminder_df = gapminder(datetimes=True, centroids=True, pretty_names=True)

gapminder_df["Year"] = gapminder_df.Year.dt.year

gapminder_df.head(15)

,Country,Continent,Year,Life Expectancy,Population,GDP per Capita,ISO Alpha Country Code,ISO Numeric Country Code,Centroid Longitude,Centroid Latitude
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4,65.0,33.0
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4,65.0,33.0
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4,65.0,33.0
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4,65.0,33.0
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4,65.0,33.0
5,Afghanistan,Asia,1977,38.438,14880372,786.113360,AFG,4,65.0,33.0
6,Afghanistan,Asia,1982,39.854,12881816,978.011439,AFG,4,65.0,33.0
7,Afghanistan,Asia,1987,40.822,13867957,852.395945,AFG,4,65.0,33.0
8,Afghanistan,Asia,1992,41.674,16317921,649.341395,AFG,4,65.0,33.0
9,Afghanistan,Asia,1997,41.763,22227415,635.341351,AFG,4,65.0,33.0
10,Afghanistan,Asia,2002,42.129,25268405,726.734055,AFG,4,65.0,33.0
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4,65.0,33.0
12,Albania,Europe,1952,55.230,1282697,1601.056136,ALB,8,20.0,41.0
13,Albania,Europe,1957,59.280,1476505,1942.284244,ALB,8,20.0,41.0
14,Albania,Europe,1962,64.820,1728137,2312.888958,ALB,8,20.0,41.0